modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "terrarium_expanded"
version = "${version}"
displayName = "terrarium_expanded"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.terrarium_expanded]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrarium_expanded]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrarium_expanded]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.terrarium_expanded]]
modId = "biomesoplenty"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.terrarium_expanded]]
modId = "regions_unexplored"
type = "optional"
versionRange = "[0.6+beta4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.terrarium_expanded]]
modId = "natures_spirit"
type = "optional"
versionRange = "[2.2.5-1.21.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "terrarium_expanded.mixins.json"
